enum RuleType {
  // Block rules
  BLOCK_OPENING_TAG = "BLOCK_OPENING_TAG",
  BLOCK_CLOSING_TAG = "BLOCK_CLOSING_TAG",
  BLOCK_SELF_CLOSING_TAG = "BLOCK_SELF_CLOSING_TAG",

  // Shortcode rules
  SHORTCODE_OPENING_TAG = "SHORTCODE_OPENING_TAG",
  SHORTCODE_CLOSING_TAG = "SHORTCODE_CLOSING_TAG",
  SHORTCODE_SELF_CLOSING_TAG = "SHORTCODE_SELF_CLOSING_TAG",
}

type RuleSet = {
  [key in RuleType]?: RegExp;
};

export { RuleType, RuleSet };
